<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Popup_Choose</name>
   <tag></tag>
   <elementGuidId>09717590-c4b5-4fb3-8ac2-f7bcaf58e618</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;previousButton_tuvvlikzpnnx&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;previousButton_tuvvlikzpnnx&quot;]</value>
   </webElementProperties>
</WebElementEntity>
