<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_into_ApprovePage</name>
   <tag></tag>
   <elementGuidId>3db18651-bb24-4f09-be2b-2b9ea34d4d59</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//table[@id='unProcList']//td[@title='0000001235']//parent::tr//td[1]//a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//table[@id='unProcList']//td[@title='0000001235']//parent::tr//td[1]//a</value>
   </webElementProperties>
</WebElementEntity>
