<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_errMsg_Approve</name>
   <tag></tag>
   <elementGuidId>45eaa537-f1c2-449f-9bd1-ae898cb44df5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id=&quot;messagebox&quot;]/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id=&quot;messagebox&quot;]/p</value>
   </webElementProperties>
</WebElementEntity>
