<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>choose_user_mail</name>
   <tag></tag>
   <elementGuidId>a3dad302-9014-42c5-9004-8868af26dd71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@title=&quot;dev04khang@dummy.com&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@title=&quot;dev04khang@dummy.com&quot;]</value>
   </webElementProperties>
</WebElementEntity>
