<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Login_button</name>
   <tag></tag>
   <elementGuidId>44ec6962-79dc-458d-83dd-e2f3c6ea9cac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;imui-gcf-container&quot;]/div/div/form/div/div[2]/div[3]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;imui-gcf-container&quot;]/div/div/form/div/div[2]/div[3]/input</value>
   </webElementProperties>
</WebElementEntity>
