<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>qa_div_1_checkbox</name>
   <tag></tag>
   <elementGuidId>a4643d5d-99af-4a11-8e3d-fa9177c5aadc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;qa_div&quot;]/label[1]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;qa_div&quot;]/label[1]/input</value>
   </webElementProperties>
</WebElementEntity>
