<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>question_value</name>
   <tag></tag>
   <elementGuidId>4e18adb5-31ed-4aba-9dc8-b85fc017c7f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[1]/form[1]/div[2]/div/div[6]/div[1]/div[1]/div[1]/div[3]/div[3]/div/table/tbody/tr[2]/td[8]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[1]/form[1]/div[2]/div/div[6]/div[1]/div[1]/div[1]/div[3]/div[3]/div/table/tbody/tr[2]/td[8]</value>
   </webElementProperties>
</WebElementEntity>
