<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>reply_questioner_button</name>
   <tag></tag>
   <elementGuidId>d6cbeefd-b349-45da-82ad-fac168cd2d30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;registButton_naxeybgmzubf&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;registButton_naxeybgmzubf&quot;]</value>
   </webElementProperties>
</WebElementEntity>
