<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>sale_com_name</name>
   <tag></tag>
   <elementGuidId>622ce079-12ff-48c0-92f6-3c25df8c1581</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;48_gt6_sales_com_nm&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;48_gt6_sales_com_nm&quot;]</value>
   </webElementProperties>
</WebElementEntity>
