<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>sale_com_text</name>
   <tag></tag>
   <elementGuidId>270c8f7a-5d5a-4ee2-9c98-847ec2fb1f46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;48_gt6_sales_com_cd&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;48_gt6_sales_com_cd&quot;]</value>
   </webElementProperties>
</WebElementEntity>
