<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>search_CustomerCode</name>
   <tag></tag>
   <elementGuidId>524353b6-499e-4a6d-8365-2bac01bf97f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;eykyzweomywv&quot;]/a[1]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;eykyzweomywv&quot;]/a[1]/span</value>
   </webElementProperties>
</WebElementEntity>
