<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Holiday</name>
   <tag></tag>
   <elementGuidId>5b1ff8ee-cdde-450e-9c9b-7f53ab7c704c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//td[contains(@class,&quot;a2019-09-16&quot;)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//td[contains(@class,&quot;a2019-09-16&quot;)]</value>
   </webElementProperties>
</WebElementEntity>
