<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_CancellClearance</name>
   <tag></tag>
   <elementGuidId>af60d15a-1e3f-4802-809e-32caeb2a2e87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;eventButton_akbtbbiclqwc&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;eventButton_akbtbbiclqwc&quot;]</value>
   </webElementProperties>
</WebElementEntity>
