<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>show_imdata</name>
   <tag></tag>
   <elementGuidId>526eecbc-4fb5-4b9e-81b8-8ff7d31500a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;nextButton_dbbbvzjpzvhp&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;nextButton_dbbbvzjpzvhp&quot;]</value>
   </webElementProperties>
</WebElementEntity>
