<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Selection_Company_Sales</name>
   <tag></tag>
   <elementGuidId>50a5e3a3-bae0-4b79-8dc4-615f4de8ed54</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id=&quot;nextButton_gnrqjsxyocax&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id=&quot;nextButton_gnrqjsxyocax&quot;]</value>
   </webElementProperties>
</WebElementEntity>
