<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Edit_Line1</name>
   <tag></tag>
   <elementGuidId>3cd2232f-c6cd-4fe5-b8f9-57d9e6236d45</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//table//tbody//tr[2]//td[3]//a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//table//tbody//tr[2]//td[3]//a</value>
   </webElementProperties>
</WebElementEntity>
