<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_DangKi_Content</name>
   <tag></tag>
   <elementGuidId>c2825d59-d68f-4f02-b370-17f08656bd6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id=&quot;eventButton_fgccqbslohvj&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id=&quot;eventButton_fgccqbslohvj&quot;]</value>
   </webElementProperties>
</WebElementEntity>
