<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_bt</name>
   <tag></tag>
   <elementGuidId>4c23a01e-593f-4a58-89f3-b2a4ede223d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;previousButton_tuvvlikzpnnx&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;previousButton_tuvvlikzpnnx&quot;]</value>
   </webElementProperties>
</WebElementEntity>
