<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_To_Mails</name>
   <tag></tag>
   <elementGuidId>6a56ed84-5f4c-4946-824c-f337e089b395</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id=&quot;nextButton_akxhyinvlaec&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id=&quot;nextButton_akxhyinvlaec&quot;]</value>
   </webElementProperties>
</WebElementEntity>
