<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textbox_Tab1_Number_Days_Elapsed</name>
   <tag></tag>
   <elementGuidId>971272f6-6205-4cfc-a0d7-ce09ae239c62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@name=&quot;num_day_elapsed&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@name=&quot;num_day_elapsed&quot;]</value>
   </webElementProperties>
</WebElementEntity>
