<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Tab3_Clear_Selected_Document</name>
   <tag></tag>
   <elementGuidId>22f89a2c-d981-4b00-aa5a-99111b55be35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id=&quot;eventButton_xadkperjrjfg&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id=&quot;eventButton_xadkperjrjfg&quot;]</value>
   </webElementProperties>
</WebElementEntity>
