<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_bt</name>
   <tag></tag>
   <elementGuidId>c5e2ea77-8cff-4ae1-a57c-84d41382f817</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;previousButton_tuvvlikzpnnx&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;previousButton_tuvvlikzpnnx&quot;]</value>
   </webElementProperties>
</WebElementEntity>
