<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Month</name>
   <tag></tag>
   <elementGuidId>63773eb3-cb39-48f3-82b5-697314662cc8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select[contains(@class,&quot;ui-datepicker-month&quot;)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//select[contains(@class,&quot;ui-datepicker-month&quot;)]</value>
   </webElementProperties>
</WebElementEntity>
