<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_AddFile</name>
   <tag></tag>
   <elementGuidId>9524a702-edad-4842-b42e-bd1417c32508</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;xgtgkstjbpxj&quot;]/table/tbody[1]/tr/th[4]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;xgtgkstjbpxj&quot;]/table/tbody[1]/tr/th[4]/a/span</value>
   </webElementProperties>
</WebElementEntity>
