<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>onclick_approve1</name>
   <tag></tag>
   <elementGuidId>7b6ff39a-443e-4edd-99c6-f0f55d9dd0b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;registButton_fsklbhfbfgxr&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;registButton_fsklbhfbfgxr&quot;]</value>
   </webElementProperties>
</WebElementEntity>
