<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Tab2_ClearSelected_Document</name>
   <tag></tag>
   <elementGuidId>64c0a2ff-25c3-4202-b72c-2aa2333b6dda</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id=&quot;eventButton_eghenmtkpnjp&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id=&quot;eventButton_eghenmtkpnjp&quot;]</value>
   </webElementProperties>
</WebElementEntity>
