<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnAddGridUpdate</name>
   <tag></tag>
   <elementGuidId>43e8ed95-f88a-4df6-a214-0704be913470</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@table_id=&quot;gt2_update_tanka_joho&quot;]//a[text()='追加']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@table_id=&quot;gt2_update_tanka_joho&quot;]//a[text()='追加']</value>
   </webElementProperties>
</WebElementEntity>
