<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>settext_newShohinCD</name>
   <tag></tag>
   <elementGuidId>ca8e70e3-6a58-4ec1-b80b-aa8f8adeb799</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;1_gt1_new_shohin_cd&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;1_gt1_new_shohin_cd&quot;]</value>
   </webElementProperties>
</WebElementEntity>
