<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_To_Admin_Page</name>
   <tag></tag>
   <elementGuidId>f4d2343b-89c4-4b36-b6cc-56f0b6b1c2f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@value=&quot;管理者画面へ&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@value=&quot;管理者画面へ&quot;]</value>
   </webElementProperties>
</WebElementEntity>
