<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>download_bt</name>
   <tag></tag>
   <elementGuidId>9dbe24be-a848-41d6-b8c0-5c30cb5397e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;eventButton_nfrnnnheoypf&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;eventButton_nfrnnnheoypf&quot;]</value>
   </webElementProperties>
</WebElementEntity>
