<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_into_UploadPage</name>
   <tag></tag>
   <elementGuidId>c09b4b0b-c96d-431c-a130-8d9efc52ddbb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//table[@id='flowList']//tr//td[text()='sf_nim001_単価登録申請(一括登録)']//parent::tr//td//a//span[@class='im-workflow-icon-matter-next']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//table[@id='flowList']//tr//td[text()='sf_nim001_単価登録申請(一括登録)']//parent::tr//td//a//span[@class='im-workflow-icon-matter-next']</value>
   </webElementProperties>
</WebElementEntity>
