<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>frame3</name>
   <tag></tag>
   <elementGuidId>2223b0cf-e088-46cc-96b0-c75ba4433bc9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//iframe[@id=&quot;IMW_PROC_MAIN&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//iframe[@id=&quot;IMW_PROC_MAIN&quot;]</value>
   </webElementProperties>
</WebElementEntity>
