<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>onclick_approve1</name>
   <tag></tag>
   <elementGuidId>c45b01ed-cc2e-4dba-abd6-8b4fdd963976</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;registButton_cdhenspiulri&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;registButton_cdhenspiulri&quot;]</value>
   </webElementProperties>
</WebElementEntity>
