<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_QA_Popup</name>
   <tag></tag>
   <elementGuidId>4c1cdb5c-4468-426e-b2e3-5ffe0f6b8d9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;btnOpenQASrc&quot;]/span/font</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;btnOpenQASrc&quot;]/span/font</value>
   </webElementProperties>
</WebElementEntity>
