<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Into_QLNV_Form</name>
   <tag></tag>
   <elementGuidId>a8523b2b-ca08-41a4-ad03-b61cac18dba8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;im_menu_tree_8fbzh9gqo5k8h&quot;]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;im_menu_tree_8fbzh9gqo5k8h&quot;]/div/a</value>
   </webElementProperties>
</WebElementEntity>
