<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Verify_Login</name>
   <tag></tag>
   <elementGuidId>1de9c24d-bad9-40b2-b28e-4828ba71b5dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;imui-user-utility&quot;]/li/a/span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;imui-user-utility&quot;]/li/a/span[1]</value>
   </webElementProperties>
</WebElementEntity>
