<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textbox_Sum_Overpay</name>
   <tag></tag>
   <elementGuidId>27fc1bf0-2aa5-4393-99dc-a1cb8b0c62ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;jhpabmxeqvpa&quot;]/input[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;jhpabmxeqvpa&quot;]/input[2]</value>
   </webElementProperties>
</WebElementEntity>
