<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>click_delete_checkbox</name>
   <tag></tag>
   <elementGuidId>4497b6a4-676a-42a9-814e-a6dbb3f0ac10</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;tanka_kubun_delete&quot;]/label/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;tanka_kubun_delete&quot;]/label/input</value>
   </webElementProperties>
</WebElementEntity>
