<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>click_regisbutton</name>
   <tag></tag>
   <elementGuidId>64c44c47-0e26-4017-b112-e972ff52806f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;eventButton_aynwcjhihiwq&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;eventButton_aynwcjhihiwq&quot;]</value>
   </webElementProperties>
</WebElementEntity>
