<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Popup_Choose_Sale_Comp</name>
   <tag></tag>
   <elementGuidId>96155325-2cc0-49ba-a9b9-0754e9bcdab9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;previousButton_tuvvlikzpnnx&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;previousButton_tuvvlikzpnnx&quot;]</value>
   </webElementProperties>
</WebElementEntity>
